name: Deploy Static Site to Xserver  # ワークフロー名

on:
  push:
    branches:
      - main  # mainブランチへのpush時にトリガーされる

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub上の仮想Linuxマシンで動く

    steps:
      # ステップ1：コードをGitHubリポジトリからチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2：SSH接続の準備（秘密鍵を使う）
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          key: ${{ secrets.XSERVER_SSH_KEY }}           # Xserver用の秘密鍵 (Secretに登録)
          passphrase: ${{ secrets.XSERVER_SSH_PASSPHRASE }} # 秘密鍵のパスフレーズ (Secretに登録)
          known_hosts: ${{ secrets.XSERVER_KNOWN_HOSTS }} # ★ Xserverのホストキーを登録 (後述)

      # ステップ3：rsyncでXserverにファイルをアップロード
      - name: Deploy static files to Xserver
        run: |
          rsync -avz --delete -e ssh ./ ${{ secrets.XSERVER_USERNAME }}@${{ secrets.XSERVER_HOSTNAME }}:${{ secrets.XSERVER_TARGET_PATH }}
