name: Deploy to Xserver          # ワークフローの名前

on:
  push:
    branches: [ "main" ]         # main へ push すると自動実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリのコードを取得
      - name: Checkout repository
        uses: actions/checkout@v3

      # ② SCP で Xserver にアップロード
      - name: Deploy to Xserver via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host:        ${{ secrets.SSH_HOST }}          # 例: xs123456.xsrv.jp
          username:    ${{ secrets.SSH_USER }}          # 例: xs123456
          port:        ${{ secrets.SSH_PORT }}          # 10022 が既定
          key:         ${{ secrets.SSH_KEY }}           # 秘密鍵全文
          passphrase:  ${{ secrets.SSH_KEY_PASSPHRASE }}# 鍵にパスフレーズを設定した場合
          source: "./**"                                # アップロード元（全ファイル）
          target: "/home/sv8161.xserver.jp/agotherapist.com/public_html"  # デプロイ先
